export enum ToolName {
    Pencil = 'Crayon',
    Spraypaint = 'Aerosol',
    Rectangle = 'Rectangle',
    Ellipse = 'Ellipse',
    Polygone = 'Polygone',
    Line = 'Ligne',
    Text = 'Texte',
    PaintBucket = 'Sceau de peinture',
    Eraser = 'Efface',
    Stamp = 'Etampe',
    Pipette = 'Pipette',
    RectangleSelection = 'Rectangle de selection',
    EllipseSelection = 'Ellipse de selection',
    LassoPolygonal = 'Lasso polygonal',
    newDrawing = 'Nouveau dessin',
    SaveDrawing = 'Sauvegarder dessin',
    SeeDrawingCaroussel = 'Caroussel de dessin',
    ExportDrawing = 'Exporter le dessin',
    Cancel = 'Annuler',
    Redo = 'Refaire',
    Copy = 'Copier',
    Cut = 'Couper',
    Paste = 'Coller',
    Homepage = "Page d'acceuil",
    ToggleGrid = 'Afficher ou masquer la grille',
    Magnetism = 'Magnetisme',
}
